name: Notify on PR to Main

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed
      - ready_for_review
      - review_requested
      - review_request_removed
      - reopened

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Đọc dữ liệu sự kiện pull request
          pr=$(jq '.pull_request' < "$GITHUB_EVENT_PATH")
          actor="$GITHUB_ACTOR"
          repo="$GITHUB_REPOSITORY"
          prNumber=$(echo "$pr" | jq -r '.number')
          action=$(jq -r '.action' < "$GITHUB_EVENT_PATH")
          prTitle=$(echo "$pr" | jq -r '.title')
          sourceBranch=$(echo "$pr" | jq -r '.head.ref')
          targetBranch=$(echo "$pr" | jq -r '.base.ref')
          prUrl=$(echo "$pr" | jq -r '.html_url')

          # Tạo nội dung tin nhắn (bỏ markdown)
          message="Pull Request Activity
          Actor: $actor
          Action: $action
          Repo: $repo
          From: $sourceBranch -> $targetBranch
          Title: $prTitle
          PR: $prUrl"

          echo "Sending Telegram message:"
          echo "$message"

          # Gửi tin nhắn tới Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$message"
